---
name: Build Wheel
on: workflow_dispatch
jobs:
  build-wheel:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Build
      run: python -m pip install build
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Wheel
      run: python -m build
